### ISSUE TITLE
WebVTT output

### ISSUE THREAD

**Issue by holzmaster** [pr0gramm-com/fluester#2]
Currently, the output looks like this:

```js
[
  {
    start: "00:00:14.310",
    end: "00:00:16.480",
    speech: "howdy"
  }
]
```

We need some way to get a valid WebVTT file from that. This stripped-down format would suffice:
```webvtt
WEBVTT

00:00:00.000 --> 00:00:02.000
howdy

00:00:30.000 --> 00:00:32.000
howdy, too!
```
Full ref: https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API

# Options
1. Provide a method that converts a `TranscriptLine[]` to a WebVTT string.
2. Depending on the options passed to `translate`/`transcribe`, also return a WebVTT string

I think option 1 would be the most practical solution. Proposed API surface:

```js
import { createWebVttString } from "@pr0gramm/fluester";

// createWebVttString(transcript: TranscriptLine[]): string;
```

**Comment by SoraTenshi** [comment]
I'd take a look at it hopefully this week.
